// SPDX-License-Identifier: Apache-2.0
//
// A runtime harness for the macOS decision engine.
//
// The macOS Network Extension has long been the weakest-verified of the three
// backends: CI type-checked its Swift, and `shared/tests/macos_wire_contract.rs`
// pinned the constants it decodes, but nothing *ran* it. Pinning a constant is
// not executing a decoder, and a decoder that only ever runs on a live macOS
// host under a signed extension is a decoder nobody checks.
//
// `RuleEngine.swift` is the exception that makes this fixable: it imports only
// Foundation, no NetworkExtension framework, so its address parsing, CIDR
// containment, zone classification, staged evaluation and glob matching — the
// whole decision core, the part that must agree with the two C kernels byte for
// byte — compile and run as a plain executable, no Xcode and no signing. This
// harness is that executable. It is built and run in CI on a macOS runner
// (`swiftc -emit-executable RuleEngine.swift RuleEngineHarness.swift`), and it
// exits non-zero, naming the property, the moment the engine disagrees with a
// hand-checked expectation.
//
// It exercises the same shapes the equivalence proof enumerates for the C
// backends — v4/v6 boundaries, the fail-closed identity asymmetry, stage
// ordering, the port-on-a-portless-protocol rule — so a divergence that a
// verdict-only comparison would miss shows up here as a failed check.

import Foundation

// The engine references the compiled-in policy through `fromGeneratedPolicy()`.
// The real definition is generated by `make generate`; the harness compiles
// RuleEngine.swift on its own, so it supplies a minimal stand-in. The harness
// never calls `fromGeneratedPolicy()` — it builds its own engines — so an empty
// policy is enough to resolve the symbol.
enum UFWGeneratedPolicy {
    static let rules: [UFWRule] = []
    static let defaultAction: UFWAction = .deny
    static let internalNetworks: [String] = []
    static let perimeterNetworks: [String] = []
    static let revision: UInt64 = 0
    static let rulesetSHA256: String = ""
}

// MARK: - Tiny check framework

var failures = 0
func check(_ condition: Bool, _ message: String) {
    if !condition {
        print("FAIL: \(message)")
        failures += 1
    }
}

func addr(_ s: String) -> UFWAddress {
    guard let a = UFWAddress(string: s) else {
        print("FAIL: address \(s) did not parse")
        failures += 1
        return .zeroV4
    }
    return a
}

/// Build a rule with only the fields a test cares about; the rest are the
/// wildcard defaults (empty lists match anything).
func rule(_ id: UInt32, _ name: String, stage: UFWStage = .packet,
          action: UFWAction, ipProtocol: UInt8 = 255,
          destPorts: [UFWPortRange] = [], sourceZones: [UFWZone] = [],
          destZones: [UFWZone] = [], destCIDRs: [String] = [],
          application: UFWAppMatch? = nil, dpi: UFWDPIMatch? = nil) -> UFWRule {
    UFWRule(id: id, name: name, stage: stage, priority: 0, provider: .flow,
            protocolScope: .all, action: action, direction: .any,
            ipProtocol: ipProtocol, sourceCIDRs: [], sourcePorts: [],
            destCIDRs: destCIDRs, destPorts: destPorts, sourceZones: sourceZones,
            destZones: destZones, application: application, dpi: dpi,
            shouldLog: false)
}

func tcp(destPort: UInt16, proto: UInt8 = 6) -> UFWFlowFacts {
    var f = UFWFlowFacts()
    f.ipProtocol = proto
    f.destPort = destPort
    return f
}

// MARK: - Address parsing

func testAddressParsing() {
    // IPv4: valid, and the malformed forms that must return nil rather than a
    // zero address that would match 0.0.0.0/0.
    check(addr("10.0.0.1").bytes == [10, 0, 0, 1], "v4 dotted-quad parses")
    check(UFWAddress(string: "1.2.3") == nil, "v4 with three parts is rejected")
    check(UFWAddress(string: "256.0.0.1") == nil, "v4 octet over 255 is rejected")
    check(UFWAddress(string: "a.b.c.d") == nil, "v4 non-numeric is rejected")

    // IPv6: loopback, a compressed form, a full form, and the malformed cases.
    check(addr("::1").bytes == [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
          "::1 parses to the loopback bytes")
    check(Array(addr("2001:db8::1").bytes.prefix(4)) == [0x20, 0x01, 0x0d, 0xb8],
          "2001:db8::1 head bytes")
    check(UFWAddress(string: "2001:db8::")?.isV6 == true, "trailing :: parses")
    check(UFWAddress(string: "1:2:3:4:5:6:7:8")?.bytes.count == 16, "full v6 is 16 bytes")
    check(UFWAddress(string: ":::") == nil, "more than one :: is rejected")
    check(UFWAddress(string: "1:2:3:4:5:6:7:8:9") == nil, "nine groups is rejected")
    check(UFWAddress(string: "1:2:3:4:5:6:7:8::") == nil,
          ":: that compresses nothing is rejected")
    check(UFWAddress(string: "gg::1") == nil, "non-hex group is rejected")
}

// MARK: - CIDR containment

func testCIDR() {
    check(UFWCIDR("10.0.0.0/8")!.contains(addr("10.255.1.1")), "10/8 contains 10.255.1.1")
    check(!UFWCIDR("10.0.0.0/8")!.contains(addr("11.0.0.1")), "10/8 excludes 11.0.0.1")
    check(UFWCIDR("192.168.1.0/24")!.contains(addr("192.168.1.254")), "/24 boundary in")
    check(!UFWCIDR("192.168.1.0/24")!.contains(addr("192.168.2.1")), "/24 boundary out")
    check(UFWCIDR("192.168.1.7/32")!.contains(addr("192.168.1.7")), "/32 exact match")
    check(!UFWCIDR("192.168.1.7/32")!.contains(addr("192.168.1.8")), "/32 rejects neighbour")
    // A sub-byte prefix exercises the mask arithmetic.
    check(UFWCIDR("10.128.0.0/9")!.contains(addr("10.200.0.1")), "/9 mask in")
    check(!UFWCIDR("10.128.0.0/9")!.contains(addr("10.100.0.1")), "/9 mask out")
    // v6, and the strict family separation that stops a v4 rule matching a v6
    // address — an ambiguity that would be a bypass.
    check(UFWCIDR("2001:db8::/32")!.contains(addr("2001:db8:1234::1")), "v6 /32 in")
    check(!UFWCIDR("2001:db8::/32")!.contains(addr("2001:dead::1")), "v6 /32 out")
    check(!UFWCIDR("10.0.0.0/8")!.contains(addr("::1")), "a v4 CIDR never matches a v6 address")
}

// MARK: - Zones

func testZones() {
    let engine = UFWRuleEngine(
        rules: [],
        defaultAction: .deny,
        internalNetworks: ["10.0.0.0/8"],
        perimeterNetworks: ["10.1.0.0/16"]
    )
    check(engine.zone(of: addr("127.0.0.1")) == .local, "127/8 is local")
    check(engine.zone(of: addr("::1")) == .local, "::1 is local")
    check(engine.zone(of: addr("10.2.3.4")) == .internal, "10.2.3.4 is internal")
    // Overlap: 10.1.x is in both the internal /8 and the perimeter /16, and
    // perimeter is the more specific classification the operator meant.
    check(engine.zone(of: addr("10.1.2.3")) == .perimeter,
          "perimeter wins over internal on overlap")
    check(engine.zone(of: addr("8.8.8.8")) == .external, "8.8.8.8 is external")
}

// MARK: - Staged evaluation

func testEvaluation() {
    let engine = UFWRuleEngine(
        rules: [
            rule(1, "deny-telnet", action: .deny, destPorts: [UFWPortRange(23, 23)]),
            rule(2, "allow-https", action: .allow, destPorts: [UFWPortRange(443, 443)]),
        ],
        defaultAction: .deny,
        internalNetworks: [],
        perimeterNetworks: []
    )

    check(engine.evaluate(tcp(destPort: 23)).action == .deny, "port 23 is denied by rule 1")
    check(engine.evaluate(tcp(destPort: 23)).ruleID == 1, "the deny names rule 1")
    check(engine.evaluate(tcp(destPort: 443)).action == .allow, "port 443 is allowed by rule 2")
    let dflt = engine.evaluate(tcp(destPort: 80))
    check(dflt.action == .deny, "an unmatched port falls to the default")
    check(dflt.ruleID == UFWSyntheticRule.policyDefault, "the default names the synthetic rule")

    // A port constraint on a protocol with no ports is unanswerable, and an
    // unanswerable predicate must not permit — so an ICMP packet to "port 23"
    // does not match the port rule and falls to the default.
    check(engine.evaluate(tcp(destPort: 23, proto: 1)).ruleID == UFWSyntheticRule.policyDefault,
          "a port rule does not match ICMP")

    // Stage ordering: a terminal allow at the packet stage returns before an
    // identity-stage deny is ever considered.
    let staged = UFWRuleEngine(
        rules: [
            rule(10, "allow-packet", stage: .packet, action: .allow,
                 destPorts: [UFWPortRange(443, 443)]),
            rule(11, "deny-identity", stage: .identity, action: .deny,
                 destPorts: [UFWPortRange(443, 443)]),
        ],
        defaultAction: .deny, internalNetworks: [], perimeterNetworks: []
    )
    let d = staged.evaluate(tcp(destPort: 443))
    check(d.action == .allow && d.ruleID == 10, "an earlier stage's terminal verdict wins")

    // allowInspect is provisional: it records a permit but keeps evaluating, and
    // with nothing terminal after it, the decision is that provisional permit.
    let inspect = UFWRuleEngine(
        rules: [rule(20, "inspect", stage: .perimeter, action: .allowInspect,
                     destPorts: [UFWPortRange(443, 443)])],
        defaultAction: .deny, internalNetworks: [], perimeterNetworks: []
    )
    let di = inspect.evaluate(tcp(destPort: 443))
    check(di.action == .allowInspect && di.ruleID == 20, "allowInspect is provisional and kept")
}

// MARK: - The fail-closed identity asymmetry

func testIdentityAsymmetry() {
    // A rule that permits a flow only from a trusted, validly-signed binary.
    // With no resolved identity the predicate is not satisfied — and crucially,
    // the flow does not slip through: it falls to the default deny.
    let engine = UFWRuleEngine(
        rules: [rule(1, "allow-trusted", stage: .identity, action: .allow,
                     destPorts: [UFWPortRange(443, 443)],
                     application: UFWAppMatch(trust: [.trusted], requireValidSignature: true))],
        defaultAction: .deny, internalNetworks: [], perimeterNetworks: []
    )
    var facts = tcp(destPort: 443)
    facts.identity = nil
    check(engine.evaluate(facts).action == .deny, "an absent identity satisfies no app predicate")

    // With a matching identity the same flow is allowed — proving the deny above
    // was the asymmetry, not the rule simply never matching.
    facts.identity = UFWIdentity(processID: 1, path: "/x", sha256: nil, teamID: nil,
                                 bundleID: nil, signer: nil, trust: .trusted,
                                 signatureValid: true)
    check(engine.evaluate(facts).action == .allow, "a matching trusted identity is allowed")

    // A negated predicate is not satisfied by an absent identity either.
    let negated = UFWRuleEngine(
        rules: [rule(2, "deny-not-ours", stage: .identity, action: .deny,
                     destPorts: [UFWPortRange(443, 443)],
                     application: UFWAppMatch(
                        fingerprints: [UFWFingerprint(teamIDs: ["ABCDE12345"])],
                        negate: true))],
        defaultAction: .allow, internalNetworks: [], perimeterNetworks: []
    )
    var noid = tcp(destPort: 443)
    noid.identity = nil
    // The deny must NOT fire on an unresolvable identity, so the default (allow)
    // stands — an absent fact does not satisfy even a negated predicate.
    check(negated.evaluate(noid).action == .allow,
          "a negated app predicate is not satisfied by an absent identity")
}

// MARK: - Ports and globs

func testPortsAndGlobs() {
    check(UFWPortRange(80, 443).contains(200), "port range contains an interior port")
    check(UFWPortRange(80, 443).contains(80), "port range includes its low bound")
    check(UFWPortRange(80, 443).contains(443), "port range includes its high bound")
    check(!UFWPortRange(80, 443).contains(444), "port range excludes just past the high bound")

    check(UFWGlob.match("*.dylib", "/usr/lib/foo.dylib"), "suffix glob matches")
    check(UFWGlob.match("/usr/*/bin", "/usr/local/bin"), "interior star matches")
    check(UFWGlob.match("a?c", "abc"), "? matches one char")
    check(!UFWGlob.match("a?c", "ac"), "? does not match zero chars")
    check(UFWGlob.match("/exact/path", "/exact/path"), "an exact pattern matches itself")
    check(!UFWGlob.match("ABC", "abc"), "macOS globbing is case-sensitive")
    // The pathological pattern the iterative matcher exists for: it must return
    // the correct answer promptly, not hang.
    check(!UFWGlob.match("*a*a*a*b", "aaaaaaaaaaaaaaaaaaaaX"),
          "a backtracking-heavy pattern terminates with the right answer")
}

// MARK: - main

// Swift permits top-level executable statements only in a file named
// main.swift; this harness is compiled alongside RuleEngine.swift, so the two
// files form a module with no main.swift, and the entry point has to be an
// explicit @main type rather than bare top-level calls. (The declarations above
// — the checks and the `failures` counter — are legal at file scope; only the
// statements that *run* them are not, which is what had kept this from
// compiling once the type-check ahead of it started passing.)
@main
enum RuleEngineHarnessMain {
    static func main() {
        testAddressParsing()
        testCIDR()
        testZones()
        testEvaluation()
        testIdentityAsymmetry()
        testPortsAndGlobs()

        if failures > 0 {
            print("\(failures) RuleEngine harness check(s) failed")
            exit(1)
        }
        print("all RuleEngine harness checks passed")
        exit(0)
    }
}
