//! Tokenizer for the Unified Policy Language.
//!
//! # Why the language looks like YAML
//!
//! Policies are read and edited by operators, reviewed in pull requests, and
//! generated by configuration management. An indentation-structured mapping
//! syntax is what that audience already knows. So UPL is a small, strictly
//! defined subset of YAML's block syntax — block mappings, block sequences,
//! flow sequences, comments, quoted and bare scalars — and nothing else. No
//! anchors, no aliases, no tags, no multi-document streams, no implicit typing.
//! Every one of those features is a way for a policy to mean something other
//! than what it looks like, which is not a property a firewall policy should
//! have.
//!
//! # Why there are no INDENT/DEDENT tokens
//!
//! The obvious design emits INDENT/DEDENT from line indentation. It breaks on
//! the single most common construct in this language:
//!
//! ```text
//! rules:
//!   - id: allow-dns
//!     action: allow
//! ```
//!
//! `action` belongs to the mapping that `id` starts, but its line indentation
//! (4) differs from `id`'s line indentation (2) — the mapping actually begins
//! at *column 5*, after the `- `. Reconstructing that from line-level
//! INDENT/DEDENT means special-casing the dash inside the lexer, which is
//! exactly the coupling a lexer should not have.
//!
//! Instead every token carries its 1-based character column and the parser
//! applies the offside rule against columns directly. The lexer stays a pure
//! function from text to a flat token stream, and `- id:` needs no special
//! case anywhere.

use crate::error::{codes, Diagnostic, Diagnostics, Span};

#[derive(Debug, Clone, PartialEq, Eq)]
pub enum TokenKind {
    /// `name:` in key position. The stored string excludes the colon.
    Key(String),
    /// A value scalar, already unquoted and unescaped.
    Scalar(String),
    /// `- ` block sequence entry marker.
    Dash,
    LBracket,
    RBracket,
    Comma,
    /// End of a logical line. Not emitted for blank or comment-only lines, and
    /// suppressed inside a flow sequence so `[a,\n b]` is one logical unit.
    Newline,
    Eof,
}

impl TokenKind {
    pub fn describe(&self) -> String {
        match self {
            TokenKind::Key(k) => format!("key `{k}`"),
            TokenKind::Scalar(s) => format!("value `{s}`"),
            TokenKind::Dash => "`-`".into(),
            TokenKind::LBracket => "`[`".into(),
            TokenKind::RBracket => "`]`".into(),
            TokenKind::Comma => "`,`".into(),
            TokenKind::Newline => "end of line".into(),
            TokenKind::Eof => "end of file".into(),
        }
    }
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Token {
    pub kind: TokenKind,
    pub span: Span,
    /// 1-based character column of the token's first character.
    pub col: u32,
    /// 1-based line number.
    pub line: u32,
    /// Whether a scalar or key was written in quotes. The parser uses this to
    /// keep `"true"` from being read as a boolean.
    pub quoted: bool,
}

impl Token {
    pub fn key(&self) -> Option<&str> {
        match &self.kind {
            TokenKind::Key(k) => Some(k),
            _ => None,
        }
    }

    pub fn scalar(&self) -> Option<&str> {
        match &self.kind {
            TokenKind::Scalar(s) => Some(s),
            _ => None,
        }
    }

    pub fn is(&self, kind: &TokenKind) -> bool {
        &self.kind == kind
    }
}

/// Characters allowed in a bare key. Anything else and the text is treated as
/// a scalar, which is how `description: Blocks a: b` keeps its colon.
fn is_key_char(c: char) -> bool {
    c.is_ascii_alphanumeric() || matches!(c, '_' | '-' | '.')
}

/// Tokenize `text`. Always returns a token stream (terminated by `Eof`); the
/// diagnostics tell you whether it is trustworthy.
pub fn tokenize(text: &str) -> (Vec<Token>, Diagnostics) {
    let mut lx = Lexer {
        tokens: Vec::new(),
        diags: Diagnostics::new(),
        flow_depth: 0,
        flow_open: Vec::new(),
    };
    lx.run(text);
    (lx.tokens, lx.diags)
}

struct Lexer {
    tokens: Vec<Token>,
    diags: Diagnostics,
    flow_depth: u32,
    /// Spans of currently open `[`, for the unclosed-sequence diagnostic.
    flow_open: Vec<Span>,
}

impl Lexer {
    fn run(&mut self, text: &str) {
        let mut byte_offset: u32 = 0;
        let mut line_no: u32 = 0;

        for raw_line in text.split_inclusive('\n') {
            line_no += 1;
            let line = raw_line.strip_suffix('\n').unwrap_or(raw_line);
            let line = line.strip_suffix('\r').unwrap_or(line);

            let chars: Vec<char> = line.chars().collect();
            // Byte offset of each character, plus a terminator entry.
            let mut offsets: Vec<u32> = Vec::with_capacity(chars.len() + 1);
            let mut acc = byte_offset;
            for c in &chars {
                offsets.push(acc);
                acc += c.len_utf8() as u32;
            }
            offsets.push(acc);

            self.scan_line(&chars, &offsets, line_no);

            byte_offset += raw_line.len() as u32;
        }

        for span in std::mem::take(&mut self.flow_open) {
            self.diags.push(
                Diagnostic::error(codes::UNCLOSED_FLOW_SEQ, span, "unclosed `[`")
                    .with_label("opened here, never closed")
                    .with_help("flow sequences must close on the same logical value, e.g. `[a, b]`"),
            );
        }

        let end = Span::point(byte_offset, line_no.max(1), 1);
        self.tokens.push(Token {
            kind: TokenKind::Eof,
            span: end,
            col: 1,
            line: line_no.max(1),
            quoted: false,
        });
    }

    fn scan_line(&mut self, chars: &[char], offsets: &[u32], line_no: u32) {
        let n = chars.len();
        let mut i = 0usize;
        let tokens_before = self.tokens.len();

        // Leading indentation. Tabs are rejected outright: a file that mixes
        // them with spaces reads differently in every editor, and a policy
        // whose meaning depends on tab width is a policy waiting to be
        // misread.
        if self.flow_depth == 0 {
            while i < n && (chars[i] == ' ' || chars[i] == '\t') {
                if chars[i] == '\t' {
                    self.diags.push(
                        Diagnostic::error(
                            codes::TAB_INDENT,
                            self.span_at(offsets, i, i + 1, line_no),
                            "tab character in indentation",
                        )
                        .with_label("tab here")
                        .with_help("indent with spaces; two per level is the project convention"),
                    );
                }
                i += 1;
            }
        }

        while i < n {
            let c = chars[i];

            if c == ' ' || c == '\t' {
                i += 1;
                continue;
            }

            // A `#` starts a comment when it opens the token or follows a
            // space. `a#b` is a scalar, `a #b` is `a` plus a comment — the
            // same rule YAML uses.
            if c == '#' && (i == 0 || chars[i - 1] == ' ' || chars[i - 1] == '\t') {
                break;
            }

            match c {
                '[' => {
                    let span = self.span_at(offsets, i, i + 1, line_no);
                    self.push(TokenKind::LBracket, span, offsets, i, line_no, false);
                    self.flow_depth += 1;
                    self.flow_open.push(span);
                    i += 1;
                }
                ']' => {
                    let span = self.span_at(offsets, i, i + 1, line_no);
                    self.push(TokenKind::RBracket, span, offsets, i, line_no, false);
                    if self.flow_depth == 0 {
                        self.diags.push(
                            Diagnostic::error(codes::STRAY_CHARACTER, span, "unmatched `]`")
                                .with_label("no `[` is open here"),
                        );
                    } else {
                        self.flow_depth -= 1;
                        self.flow_open.pop();
                    }
                    i += 1;
                }
                ',' if self.flow_depth > 0 => {
                    let span = self.span_at(offsets, i, i + 1, line_no);
                    self.push(TokenKind::Comma, span, offsets, i, line_no, false);
                    i += 1;
                }
                '-' if self.flow_depth == 0
                    && (i + 1 >= n || chars[i + 1] == ' ' || chars[i + 1] == '\t') =>
                {
                    let span = self.span_at(offsets, i, i + 1, line_no);
                    self.push(TokenKind::Dash, span, offsets, i, line_no, false);
                    i += 1;
                }
                '"' | '\'' => {
                    i = self.scan_quoted(chars, offsets, line_no, i);
                }
                _ => {
                    i = self.scan_bare(chars, offsets, line_no, i);
                }
            }
        }

        // Only a line that produced tokens terminates a logical line, and only
        // outside a flow sequence.
        if self.flow_depth == 0 && self.tokens.len() > tokens_before {
            let span = Span::point(offsets[n], line_no, n as u32 + 1);
            self.tokens.push(Token {
                kind: TokenKind::Newline,
                span,
                col: n as u32 + 1,
                line: line_no,
                quoted: false,
            });
        }
    }

    /// Scan a quoted scalar, then decide whether a `:` turns it into a key.
    fn scan_quoted(
        &mut self,
        chars: &[char],
        offsets: &[u32],
        line_no: u32,
        start: usize,
    ) -> usize {
        let quote = chars[start];
        let n = chars.len();
        let mut i = start + 1;
        let mut value = String::new();
        let mut terminated = false;

        while i < n {
            let c = chars[i];
            if c == quote {
                // In a single-quoted scalar, a doubled quote is a literal one.
                if quote == '\'' && i + 1 < n && chars[i + 1] == '\'' {
                    value.push('\'');
                    i += 2;
                    continue;
                }
                terminated = true;
                i += 1;
                break;
            }
            if quote == '"' && c == '\\' {
                i += 1;
                if i >= n {
                    break;
                }
                match chars[i] {
                    'n' => value.push('\n'),
                    't' => value.push('\t'),
                    'r' => value.push('\r'),
                    '0' => value.push('\0'),
                    '\\' => value.push('\\'),
                    '"' => value.push('"'),
                    '/' => value.push('/'),
                    'u' => {
                        let mut cp: u32 = 0;
                        let mut digits = 0;
                        while digits < 4 && i + 1 < n && chars[i + 1].is_ascii_hexdigit() {
                            i += 1;
                            cp = cp * 16 + chars[i].to_digit(16).unwrap();
                            digits += 1;
                        }
                        match (digits == 4).then(|| char::from_u32(cp)).flatten() {
                            Some(ch) => value.push(ch),
                            None => self.diags.push(
                                Diagnostic::error(
                                    codes::BAD_ESCAPE,
                                    self.span_at(offsets, start, i + 1, line_no),
                                    "invalid `\\u` escape",
                                )
                                .with_help("write four hexadecimal digits, e.g. `\\u00e9`"),
                            ),
                        }
                    }
                    other => {
                        self.diags.push(
                            Diagnostic::error(
                                codes::BAD_ESCAPE,
                                self.span_at(offsets, i - 1, i + 1, line_no),
                                format!("unknown escape `\\{other}`"),
                            )
                            .with_help(
                                "supported escapes are \\n \\t \\r \\0 \\\\ \\\" \\/ and \\uXXXX",
                            ),
                        );
                        value.push(other);
                    }
                }
                i += 1;
                continue;
            }
            value.push(c);
            i += 1;
        }

        if !terminated {
            self.diags.push(
                Diagnostic::error(
                    codes::UNTERMINATED_STRING,
                    self.span_at(offsets, start, n, line_no),
                    "unterminated quoted string",
                )
                .with_label("string starts here and never closes")
                .with_help("the language has no multi-line scalars; keep quotes on one line"),
            );
        }

        // `"key": value`
        let mut j = i;
        while j < n && chars[j] == ' ' {
            j += 1;
        }
        if j < n && chars[j] == ':' && self.colon_ends_key(chars, j) {
            let span = self.span_at(offsets, start, j + 1, line_no);
            self.push(TokenKind::Key(value), span, offsets, start, line_no, true);
            return j + 1;
        }

        let span = self.span_at(offsets, start, i, line_no);
        self.push(TokenKind::Scalar(value), span, offsets, start, line_no, true);
        i
    }

    /// A colon closes a key when what follows is whitespace, end of line, or —
    /// inside a flow sequence — a separator. `http://x` therefore stays one
    /// scalar, while `path:` is a key.
    fn colon_ends_key(&self, chars: &[char], at: usize) -> bool {
        match chars.get(at + 1) {
            None => true,
            Some(' ') | Some('\t') => true,
            Some(',') | Some(']') if self.flow_depth > 0 => true,
            _ => false,
        }
    }

    /// Scan an unquoted token: either `key:` or a scalar running to the end of
    /// the line (or to the next flow separator).
    fn scan_bare(
        &mut self,
        chars: &[char],
        offsets: &[u32],
        line_no: u32,
        start: usize,
    ) -> usize {
        let n = chars.len();

        // First, look for a key terminator without consuming anything.
        let mut j = start;
        let mut key_end: Option<usize> = None;
        while j < n {
            let c = chars[j];
            if c == '#' && j > start && (chars[j - 1] == ' ' || chars[j - 1] == '\t') {
                break;
            }
            if self.flow_depth > 0 && (c == ',' || c == ']') {
                break;
            }
            if c == ':' && self.colon_ends_key(chars, j) {
                key_end = Some(j);
                break;
            }
            j += 1;
        }

        if let Some(end) = key_end {
            let text: String = chars[start..end].iter().collect();
            let trimmed = text.trim_end();
            if !trimmed.is_empty() && trimmed.chars().all(is_key_char) {
                let span = self.span_at(offsets, start, end + 1, line_no);
                self.push(
                    TokenKind::Key(trimmed.to_string()),
                    span,
                    offsets,
                    start,
                    line_no,
                    false,
                );
                return end + 1;
            }
            // Not identifier-shaped: fall through and take it as a scalar, so
            // free text keeps its colons.
        }

        // Scalar: run to end of line, a comment, or a flow separator.
        let mut k = start;
        while k < n {
            let c = chars[k];
            if c == '#' && k > start && (chars[k - 1] == ' ' || chars[k - 1] == '\t') {
                break;
            }
            if self.flow_depth > 0 && (c == ',' || c == ']') {
                break;
            }
            k += 1;
        }

        let text: String = chars[start..k].iter().collect();
        let trimmed_len = text.trim_end().chars().count();
        let end = start + trimmed_len;
        let value = text.trim_end().to_string();

        if value.is_empty() {
            // Nothing consumable here; step past to guarantee progress.
            return start + 1;
        }

        let span = self.span_at(offsets, start, end, line_no);
        self.push(TokenKind::Scalar(value), span, offsets, start, line_no, false);
        k
    }

    fn span_at(&self, offsets: &[u32], start: usize, end: usize, line_no: u32) -> Span {
        let s = offsets[start.min(offsets.len() - 1)];
        let e = offsets[end.min(offsets.len() - 1)];
        Span::new(s, e, line_no, start as u32 + 1)
    }

    fn push(
        &mut self,
        kind: TokenKind,
        span: Span,
        _offsets: &[u32],
        col_index: usize,
        line_no: u32,
        quoted: bool,
    ) {
        self.tokens.push(Token {
            kind,
            span,
            col: col_index as u32 + 1,
            line: line_no,
            quoted,
        });
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn kinds(src: &str) -> Vec<TokenKind> {
        let (tokens, diags) = tokenize(src);
        assert!(
            !diags.has_errors(),
            "unexpected lexer errors: {:?}",
            diags.codes()
        );
        tokens.into_iter().map(|t| t.kind).collect()
    }

    fn key(s: &str) -> TokenKind {
        TokenKind::Key(s.into())
    }

    fn scalar(s: &str) -> TokenKind {
        TokenKind::Scalar(s.into())
    }

    #[test]
    fn simple_mapping() {
        assert_eq!(
            kinds("version: 1\n"),
            vec![key("version"), scalar("1"), TokenKind::Newline, TokenKind::Eof]
        );
    }

    #[test]
    fn blank_lines_and_comments_produce_nothing() {
        let src = "# leading comment\n\n   \nversion: 1  # trailing\n";
        assert_eq!(
            kinds(src),
            vec![key("version"), scalar("1"), TokenKind::Newline, TokenKind::Eof]
        );
    }

    #[test]
    fn hash_without_leading_space_is_not_a_comment() {
        assert_eq!(
            kinds("tag: red#blue\n"),
            vec![key("tag"), scalar("red#blue"), TokenKind::Newline, TokenKind::Eof]
        );
    }

    #[test]
    fn sequence_entries() {
        let src = "rules:\n  - allow\n  - deny\n";
        assert_eq!(
            kinds(src),
            vec![
                key("rules"),
                TokenKind::Newline,
                TokenKind::Dash,
                scalar("allow"),
                TokenKind::Newline,
                TokenKind::Dash,
                scalar("deny"),
                TokenKind::Newline,
                TokenKind::Eof,
            ]
        );
    }

    #[test]
    fn dash_needs_trailing_space_so_negative_numbers_survive() {
        assert_eq!(
            kinds("offset: -5\n"),
            vec![key("offset"), scalar("-5"), TokenKind::Newline, TokenKind::Eof]
        );
    }

    #[test]
    fn flow_sequences_ignore_line_breaks() {
        let src = "ports: [80,\n  443,\n  8000-8100]\n";
        assert_eq!(
            kinds(src),
            vec![
                key("ports"),
                TokenKind::LBracket,
                scalar("80"),
                TokenKind::Comma,
                scalar("443"),
                TokenKind::Comma,
                scalar("8000-8100"),
                TokenKind::RBracket,
                TokenKind::Newline,
                TokenKind::Eof,
            ]
        );
    }

    #[test]
    fn colons_inside_values_are_preserved() {
        // A colon only closes a key when followed by whitespace or EOL.
        assert_eq!(
            kinds("url: https://example.test/a:b\n"),
            vec![
                key("url"),
                scalar("https://example.test/a:b"),
                TokenKind::Newline,
                TokenKind::Eof
            ]
        );
        assert_eq!(
            kinds("hash: sha256:deadbeef\n"),
            vec![key("hash"), scalar("sha256:deadbeef"), TokenKind::Newline, TokenKind::Eof]
        );
    }

    #[test]
    fn free_text_with_a_colon_stays_a_scalar() {
        // `Blocks x: y` is not identifier-shaped, so it does not become a key.
        assert_eq!(
            kinds("description: Blocks x: y\n"),
            vec![
                key("description"),
                scalar("Blocks x: y"),
                TokenKind::Newline,
                TokenKind::Eof
            ]
        );
    }

    #[test]
    fn windows_paths_lex_as_one_scalar() {
        assert_eq!(
            kinds(r"path: C:\Program Files\App\app.exe" .to_string().as_str()),
            vec![
                key("path"),
                scalar(r"C:\Program Files\App\app.exe"),
                TokenKind::Newline,
                TokenKind::Eof
            ]
        );
    }

    #[test]
    fn quoted_scalars_are_unescaped() {
        assert_eq!(
            kinds("name: \"a\\nb\\t\\\"c\\\"\"\n"),
            vec![key("name"), scalar("a\nb\t\"c\""), TokenKind::Newline, TokenKind::Eof]
        );
        assert_eq!(
            kinds("name: \"caf\\u00e9\"\n"),
            vec![key("name"), scalar("café"), TokenKind::Newline, TokenKind::Eof]
        );
    }

    #[test]
    fn single_quotes_are_literal_with_doubling() {
        assert_eq!(
            kinds("name: 'a\\nb'\n"),
            vec![key("name"), scalar("a\\nb"), TokenKind::Newline, TokenKind::Eof]
        );
        assert_eq!(
            kinds("name: 'it''s'\n"),
            vec![key("name"), scalar("it's"), TokenKind::Newline, TokenKind::Eof]
        );
    }

    #[test]
    fn quoted_keys_are_supported() {
        assert_eq!(
            kinds("\"my key\": 1\n"),
            vec![key("my key"), scalar("1"), TokenKind::Newline, TokenKind::Eof]
        );
    }

    #[test]
    fn quoted_scalar_keeps_its_quoted_flag() {
        let (tokens, _) = tokenize("a: \"true\"\nb: true\n");
        let quoted: Vec<bool> = tokens
            .iter()
            .filter(|t| matches!(t.kind, TokenKind::Scalar(_)))
            .map(|t| t.quoted)
            .collect();
        assert_eq!(quoted, vec![true, false]);
    }

    #[test]
    fn columns_track_the_offside_rule_through_a_dash() {
        let src = "rules:\n  - id: allow-dns\n    action: allow\n";
        let (tokens, _) = tokenize(src);
        let find = |k: &str| {
            tokens
                .iter()
                .find(|t| t.key() == Some(k))
                .unwrap_or_else(|| panic!("no key {k}"))
        };
        assert_eq!((find("rules").line, find("rules").col), (1, 1));
        // `id` starts at column 5, after "  - ".
        assert_eq!((find("id").line, find("id").col), (2, 5));
        // `action` lines up with it, which is what makes them siblings.
        assert_eq!((find("action").line, find("action").col), (3, 5));
    }

    #[test]
    fn spans_point_at_the_right_bytes() {
        let src = "version: 1\n";
        let (tokens, _) = tokenize(src);
        let v = &tokens[1];
        assert_eq!(v.scalar(), Some("1"));
        assert_eq!(&src[v.span.start as usize..v.span.end as usize], "1");
    }

    #[test]
    fn spans_survive_multibyte_characters() {
        let src = "name: café\nnext: 2\n";
        let (tokens, _) = tokenize(src);
        let next = tokens.iter().find(|t| t.key() == Some("next")).unwrap();
        assert_eq!(next.line, 2);
        assert_eq!(next.col, 1);
        assert_eq!(&src[next.span.start as usize..next.span.end as usize], "next:");
    }

    #[test]
    fn tabs_in_indentation_are_rejected() {
        let (_, diags) = tokenize("a:\n\tb: 1\n");
        assert!(diags.has_code(codes::TAB_INDENT));
    }

    #[test]
    fn unterminated_string_is_reported() {
        let (_, diags) = tokenize("name: \"oops\n");
        assert!(diags.has_code(codes::UNTERMINATED_STRING));
    }

    #[test]
    fn unknown_escape_is_reported_but_lexing_continues() {
        let (tokens, diags) = tokenize("name: \"a\\qb\"\nnext: 1\n");
        assert!(diags.has_code(codes::BAD_ESCAPE));
        assert!(tokens.iter().any(|t| t.key() == Some("next")));
    }

    #[test]
    fn unclosed_flow_sequence_is_reported() {
        let (_, diags) = tokenize("ports: [80, 443\n");
        assert!(diags.has_code(codes::UNCLOSED_FLOW_SEQ));
    }

    #[test]
    fn stray_close_bracket_is_reported() {
        let (_, diags) = tokenize("ports: ]\n");
        assert!(diags.has_code(codes::STRAY_CHARACTER));
    }

    #[test]
    fn a_bracket_inside_a_bare_scalar_stays_part_of_it() {
        // Outside a flow sequence, `]` is an ordinary character. Only a `]`
        // in token position can be a stray delimiter.
        assert_eq!(
            kinds("note: array[0]\n"),
            vec![key("note"), scalar("array[0]"), TokenKind::Newline, TokenKind::Eof]
        );
    }

    #[test]
    fn crlf_line_endings_are_handled() {
        assert_eq!(
            kinds("version: 1\r\nname: x\r\n"),
            vec![
                key("version"),
                scalar("1"),
                TokenKind::Newline,
                key("name"),
                scalar("x"),
                TokenKind::Newline,
                TokenKind::Eof,
            ]
        );
    }

    #[test]
    fn empty_input_yields_only_eof() {
        assert_eq!(kinds(""), vec![TokenKind::Eof]);
    }

    #[test]
    fn trailing_whitespace_is_trimmed_from_scalars() {
        assert_eq!(
            kinds("name: value   \n"),
            vec![key("name"), scalar("value"), TokenKind::Newline, TokenKind::Eof]
        );
    }

    #[test]
    fn nested_dash_then_key_on_same_line_lexes_cleanly() {
        let src = "  - id: a\n";
        assert_eq!(
            kinds(src),
            vec![
                TokenKind::Dash,
                key("id"),
                scalar("a"),
                TokenKind::Newline,
                TokenKind::Eof
            ]
        );
    }

    #[test]
    fn lexer_always_terminates_on_hostile_input() {
        // Regression guard: every scan path must consume at least one char.
        for src in [":", "::", " : ", "-", "--", "[", "]", "[,]", "\"", "'", "\\"] {
            let (tokens, _) = tokenize(src);
            assert_eq!(tokens.last().unwrap().kind, TokenKind::Eof);
        }
    }
}
